args: new display option

diff --git a/gsu b/gsu
--- a/gsu
+++ b/gsu
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION="1.0.1"
+VERSION="1.0.1-git"
 config_path="${XDG_CONFIG_HOME:-${HOME}/.config}/gsu"
 
 print_help() {
@@ -9,18 +9,20 @@ Usage: gsu [OPTION]... SOURCE
 A general screenshot and upload utility for images, video, and gifs.
 
 GENERAL OPTIONS
-  -h, --help              Show the help menu
-  -v, --version           Show the current version
+  -h, --help                 Show the help menu
+  -v, --version              Show the current version
 
-  -u, --upload            Upload after running the utility
-  -n, --nocursor          Hide the cursor
+  -u, --upload               Upload after running the utility
+  -n, --nocursor             Hide the cursor
+  -d, --display NUM|TYPE     Set the selection to a specific display
+                             Values: number of display, 'active', 'all' (default)
 
-  -s, --screenshot        Take a screenshot
-  -m, --video             Record a video of the screen
-  -g, --gif               Record a video and convert it to the gif format
+  -s, --screenshot           Take a screenshot
+  -m, --video                Record a video of the screen
+  -g, --gif                  Record a video and convert it to the gif format
 
 VIDEO OPTIONS
-  -c, --countdown NUM     Countdown before recording"
+  -c, --countdown NUM        Countdown before recording"
 
 	exit 0
 }
@@ -79,6 +81,7 @@ get_args() {
 			"-h" | "--help") print_help ;;
 			"-v" | "--version") print_version ;;
 			"-u" | "--upload") upload="$1" ;;
+			"-d" | "--display") display="$2" ;;
 			"-s" | "--screenshot") set_type "screenshot" ;;
 			"-m" | "--video") set_type "video" ;;
 			"-g" | "--gif") set_type "gif" ;;
@@ -128,6 +131,114 @@ get_config() {
 	source "$config_path/config.conf"
 }
 
+get_command() {
+	local MONW="0"
+	local MONH="0"
+	local MONX="0"
+	local MONY="0"
+
+	if [[ ! -z "$display" ]]; then
+		if ! type -p xrandr >/dev/null; then
+			print_missing_deps "xrandr"
+		fi
+
+		if ! type -p xdotool >/dev/null; then
+			print_missing_deps "xdotool"
+		fi
+
+		local MONITORS=$(xrandr | grep -o "[0-9]*x[0-9]*[+-][0-9]*[+-][0-9]*")
+		local XMOUSE=$(xdotool getmouselocation | awk -F "[: ]" '{print $2}')
+		local YMOUSE=$(xdotool getmouselocation | awk -F "[: ]" '{print $4}')
+
+		readarray -t MONITORS <<< "$MONITORS"
+
+		for ((i = 0; i < ${#MONITORS[@]}; i++)); do
+			local mon="${MONITORS[$i]}"
+
+			local TEMPMONW=$(echo -e $mon | awk -F "[x+]" '{print $1}')
+			local TEMPMONH=$(echo -e $mon | awk -F "[x+]" '{print $2}')
+			local TEMPMONX=$(echo -e $mon | awk -F "[x+]" '{print $3}')
+			local TEMPMONY=$(echo -e $mon | awk -F "[x+]" '{print $4}')
+
+			case "$display" in
+				"active")
+					if (( $XMOUSE >= $TEMPMONX )); then
+						if (( $XMOUSE <= $TEMPMONX+$TEMPMONW )); then
+							if (( $YMOUSE >= $TEMPMONY )); then
+								if (( $YMOUSE <= $TEMPMONY+$TEMPMONH )); then
+									MONW=$TEMPMONW
+									MONH=$TEMPMONH
+									MONX=$TEMPMONX
+									MONY=$TEMPMONY
+								fi
+							fi
+						fi
+					fi
+				;;
+
+				*)
+					if [[ $desktop =~ ^[0-9]+$ ]]; then
+						echo "num!"
+					else
+						if (($TEMPMONW > $MONW)); then
+							((MONW=$MONW + $TEMPMONW))
+						fi
+
+						if (($TEMPMONH > $MONH)); then
+							((MONH=$MONH + $TEMPMONH))
+						fi
+
+						if (($TEMPMONX + $TEMPMONW >= $MONW)); then
+							((MONW=$TEMPMONW + $TEMPMONX))
+						fi
+
+						if (($TEMPMONY + $TEMPMONH >= $MONH)); then
+							((MONH=$TEMPMONH + $TEMPMONY))
+						fi
+					fi
+				;;
+			esac
+		done
+
+		if [[ "$MONW" == "0" ]] && [[ "$MONH" == "0" ]] && [[ "$MONX" == "0" ]] && [[ "$MONY" == "0" ]]; then
+			echo "gsu: unable to find your display"
+			exit 1
+		fi
+	fi
+
+	case "$type" in
+		"screenshot")
+			if [[ -z "$display" ]]; then
+				cmd="$(maim $nocursor -s "$operand" 2>&1>/dev/null)"
+			else
+				cmd="$(maim $nocursor -g "${MONW}x${MONH}+${MONX}+${MONY}" "$operand" 2>&1>/dev/null)"
+			fi
+		;;
+
+		"video")
+			if [[ -z "$display" ]]; then
+				read -r X Y W H G ID < <(slop -f "%x %y %w %h %g %i")
+
+				if [[ -z "$X" ]] || [[ -z "$Y" ]] || [[ -z "$W" ]] || [[ -z "$H" ]]; then
+					print_manually_quit
+				fi
+			fi
+
+			if [[ ! -z "$countdown_enable" ]]; then
+				countdown "$countdown_enable" "Handing control over to ffmpeg in COUNTNUM seconds."
+			fi
+
+			echo "Press [q] or [Ctrl+C] to stop recording."
+
+			if [[ -z "$display" ]]; then
+				cmd=$(ffmpeg -y -f alsa -i pulse -r 30 -f x11grab $draw_mouse -s "$W"x"$H" -i :0.0+$X,$Y -c:v libx264 -crf 18 -preset:v ultrafast -c:a aac -b:a 192k -loglevel error "$output" 2>&1>/dev/null)
+			else
+				cmd=$(ffmpeg -y -f alsa -i pulse -r 30 -f x11grab $draw_mouse -s "$MONW"x"$MONH" -i :0.0+$MONX,$MONY -c:v libx264 -crf 18 -preset:v ultrafast -c:a aac -b:a 192k -loglevel error "$output" 2>&1>/dev/null)
+			fi
+		;;
+	esac
+}
+
 set_type() {
 	if [[ -z "$type" ]]; then
 		type="$1"
@@ -156,7 +267,7 @@ take_screenshot() {
 		print_missing_deps "maim"
 	fi
 
-	local cmd=$(maim $nocursor -s "$operand" 2>&1>/dev/null)
+	get_command
 
 	if [[ ! -z "$cmd" ]]; then
 		if [[ "$cmd" == *"keystroke or right-click"* ]]; then
@@ -187,19 +298,7 @@ take_video() {
 		output="$operand.mp4"
 	fi
 
-	read -r X Y W H G ID < <(slop -f "%x %y %w %h %g %i")
-
-	if [[ -z "$X" ]] || [[ -z "$Y" ]] || [[ -z "$W" ]] || [[ -z "$H" ]]; then
-		print_manually_quit
-	fi
-
-	if [[ ! -z "$countdown_enable" ]]; then
-		countdown "$countdown_enable" "Handing control over to ffmpeg in COUNTNUM seconds."
-	fi
-
-	echo "Press [q] or [Ctrl+C] to stop recording."
-
-	local cmd=$(ffmpeg -y -f alsa -i pulse -r 30 -f x11grab $draw_mouse -s "$W"x"$H" -i :0.0+$X,$Y -c:v libx264 -crf 18 -preset:v ultrafast -c:a aac -b:a 192k -loglevel error "$output" 2>&1>/dev/null)
+	get_command
 
 	if [[ -z "$cmd" ]]; then
 		echo "Stopped recording."
@@ -242,6 +341,10 @@ upload() {
 	local absolute="$PWD/$(basename $operand)"
 	popd &>/dev/null
 
+	if ! type -p jq >/dev/null; then
+		print_missing_deps "jq"
+	fi
+
 	local cmd
 
 	case "$type" in
@@ -255,10 +358,6 @@ upload() {
 
 		"video")
 			if [[ -z "$V_UPLOAD" ]]; then
-				if ! type -p jq >/dev/null; then
-					print_missing_deps "jq"
-				fi
-
 				if [[ -z "$STREAMABLE_USER" ]] || [[ -z "$STREAMABLE_PASS" ]]; then
 					echo -e "\ngsu: invalid streamable credentials"
 					echo "Fill in your credentials in '$config_path/config.conf' and try again."
